#!/bin/sh
# Part of spindle http://asbradbury.org/projects/spindle
#
# See LICENSE file for copyright and license details

set -ex

. ./common

CURIMG=stage4-lxde.$IMGFORMAT

install_packages() {
  # we may want to break out DEBIAN_FRONTEND=noninteractive
  ssh_in_to_qemu chroot /mnt sh -l -ex - <<EOF
apt-get update
apt-get install --no-install-recommends -y nginx-light

EOF
}


configure_tedsen() {
  ssh_in_to_qemu chroot /mnt sh -l -ex - <<EOF
cat <<EOF2 >> /etc/fstab
/dev/mmcblk0p3  /box               ext4    defaults,noatime  0       1
EOF2

EOF

  
}


configure_nginx() {
  ssh_in_to_qemu chroot /mnt sh -l -ex - <<EOF
sudo sed -i "s/worker_processes 4;/worker_processes 1;/g" /etc/nginx/nginx.conf
sudo sed -i "s/worker_connections 768;/worker_connections 128;/g" /etc/nginx/nginx.conf

# remove default website
rm /etc/nginx/sites-enabled/default

# write nginx config for tedsen-box static files
cat <<EOF2 > /etc/nginx/sites-enabled/tedsen-box
server {
  listen   80 default_server;
  
  root /box/current/public;
  index index.html index.htm;
  
}
EOF2

EOF

}


install_node() {
  onvm_chroot sh -l -e - <<\EOF
cd /tmp
# install node
wget https://www.dropbox.com/s/fh0fj9wynzz4ii2/node_0.10.28-1_armhf.deb 
dpkg -i node_0.10.28-1_armhf.deb
rm node_0.10.28-1_armhf.deb

#install coffee-script
npm install coffee-script@1.7.1 -g

mkdir -p /box/shared
chown -R pi /box
chgrp -R pi /box

cat <<EOF2 > /etc/init/tedsen-box-production.conf
#!upstart
description "tedsen-box node app"
author      "Bjoern Grossmann COKRON innovations GmbH"

start on runlevel [2345]
stop on shutdown

respawn
# try restarting 250 times in 600 seconds. if that fails, it is no longer tried
respawn limit 250 600 

script
    cd /box/current && exec sudo -u pi NODE_ENV=production PORT=3000 /usr/local/bin/coffee /box/current/server.coffee 2>> /box/shared/production.err.log 1>> /box/shared/production.out.log
end script
EOF2


EOF
}

cd $WORKDIR
dotask branch_image ../$OUTDIR/stage3.$IMGFORMAT $CURIMG
dotask run_qemu $CURIMG
dotask mount_apt_cache
dotask disable_starting_services
dotask install_packages
dotask configure_tedsen
dotask configure_nginx
dotask install_node
dotask save_space_using_hardlink
dotask allow_starting_services
dotask update_issue
dotask fingerprint_debian
dotask shutdown_qemu
dotask finish_image
